### ISSUE TITLE
Fix starting orientations of the cameras

### ISSUE THREAD

**Issue by TizioMaurizio** [VDP-noclip/noclip#100]
I tried some stuff but it's better to leave it, someone that knows better about the orientation should look into it and fix it.
Eventually it should be possible to easily change the player initial spawning orientation from the editor and when switching to noclip the camera should keep looking where it was looking before.

**Comment by spig95** [comment]
The first part of the issue should be solved here https://github.com/VDP-noclip/noclip/pull/105

**Comment by TizioMaurizio** [comment]
ah yes there is still the starting orientation to be fixed so we will close this later

**Comment by stefanofossati** [comment]
Can we close this issue? @spig95

**Comment by TizioMaurizio** [comment]
> ah yes there is still the starting orientation to be fixed so we will close this later

@stefanofossati 😝

**Comment by bottolo** [comment]
I suggest opening another issue in order to link it to another branch!

**Comment by spig95** [comment]
> I suggest opening another issue in order to link it to another branch!

I think we can link another branch to the same issue, but feel free to open a new issue to link a new branch if you think it's clearer
