### ISSUE TITLE
Solve two listener Unity warning

### ISSUE THREAD

**Issue by stefanofossati** [VDP-noclip/noclip#106]
Unity shows a warning about the fact that there are two audio listener in the scene

**Comment by stefanofossati** [comment]
I was checking the warnings that are present in our project when we start from 0_Main scene:
- More than one eventlistener, so event manager
- More than one audio listener

The best place in which put only one of these elements is the 0_Main scene. But we maybe could have problems during the developing of a separete scene. 

Conclusion: 
In order to do something useful, I think that the best solution is the following:
Leave the event manager and the audio listener in the different scenes, but push in develop that scene only with its event manager and its audio listener disabled. 
Add the only one audio listener and event manager in 0_Main

@bottolo @spig95 @TizioMaurizio @AleDeNic

**Comment by bottolo** [comment]
A little finnicky and mechanical, but it may do the trick. I don't really have further suggestions on the topic...

**Comment by bottolo** [comment]
I don't know. It seems a bit counterintuitive... everything is disabled, but in order to test with pause and feedback you'll need at least two listeners in a scene (Pause + SceneWithPlayer)

**Comment by bottolo** [comment]
Okay, after clearing things out with @stefanofossati I was actually the one who didn't fully understand this, however there was a minor thing to fix in order to make the menu work

**Comment by TizioMaurizio** [comment]
Is this solved? I just red the title so don't blame me if I said something stupid hahaha
