### ISSUE TITLE
Possibility to select and manage different input device

### ISSUE THREAD

**Issue by stefanofossati** [VDP-noclip/noclip#107]
We have spoken abuot the possibility of using a gamepad/joystick instead of mouse + keyboard.

Alse learn about the best way to do it. Suggestion: mybe with a scriptable object or Unity also has implemented it

**Comment by TizioMaurizio** [comment]
the current controls in this game are:
-move (WASD)
-jump (Space)
-nolip move (QWASDE 🤢)
-walk (Shift)
-noclip (right mouse)
-pause (L 🤠)  
-crouch (Ctrl, very important)
  
Am i missing something?
Maybe some buttons that work to navigate the menus?
  
Anyway I think the best way to manage this is to check the user inputs in the project settings, we already use them for walking (wasd are not explicit in the code, we use input movement axes instead)
