### ISSUE TITLE
Controls on the menu / pause menu

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#110]
I've closed the issue regarding trigger events and controls, since it's now working as intended.
This is an issue for controls showing in both menus in order to let the player consult them whenever he/she (_insert various pronouns here_) likes.

**Comment by TizioMaurizio** [comment]
Since this is a demo people will literally play once I would even keep them on screen in a non intrusive way, and if actually needed give a key to hide them

**Comment by bottolo** [comment]
> Since this is a demo people will literally play once I would even keep them on screen in a non intrusive way, and if actually needed give a key to hide them

Seems like a good idea. I'll see about that and maybe add you as a reviewer in the upcoming PR.
