### ISSUE TITLE
Player is too small

### ISSUE THREAD

**Issue by TizioMaurizio** [VDP-noclip/noclip#117]
As reported by some testers when playing it feels like you are too small, we should either make the player bigger or the world smaller

**Comment by TizioMaurizio** [comment]
This is being worked in [Ale](https://github.com/VDP-noclip/noclip/tree/AleDeNic/puzzles_v4) 's branch

**Comment by TizioMaurizio** [comment]
While fixing take into account that ground check is hardcoded

**Comment by stefanofossati** [comment]
> While fixing take into account that ground check is hardcoded

So we have to fix both the player size and the ground check, right?

**Comment by TizioMaurizio** [comment]
> > While fixing take into account that ground check is hardcoded
> 
> So we have to fix both the player size and the ground check, right?

ideally the player should be bigger and still work as before, how is up to who handles the issue
