### ISSUE TITLE
After respawn, make the player point toward the next goal platform

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#131]
After a respawn, we should check if there is an `endAnchor` in the current puzzle and, if so, set the rotation such that the player looks toward that anchor. 

Option 1: I guess we could ask to `ReactToPlayerCollision` to return the `endAnchor` location, and pass it as an optional argument to the `UpdateCheckpointValues`

Option 2: trigger an event to change the rotation, react to the event in mouselook. I think the second one is easier to implement

**Comment by TizioMaurizio** [comment]
Maybe the next checkpoint could disorient if the checkpoint is below, the player should point the direction of progress for the current puzzle, so then we need a **_definition for the direction of progress_**. (@AleDeNic )
Regardless it should be something that is not disorienting

**Comment by TizioMaurizio** [comment]
note that right now it stores the orientation when you unlock a checkpoint and then always uses that on respawn, so we really have to change which orientation is stored, then it will automatically use that when respawning

**Comment by TizioMaurizio** [comment]
UpdateCpValuesCoroutine() ---> _lastCheckPointRotation
(line 71)
