### ISSUE TITLE
Change anchor color after the player touches it

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#132]
I know that in the future @AleDeNic wants it to have special effects and also change shape, but for the demo it's enough to make it change color.

**Comment by TizioMaurizio** [comment]
Anyway for now actually there is already the beam of light pointing which checkpoint you should reach, we can still change the color of the platform if it's not clear enough but I would play on the beam, maybe make it way taller

**Comment by spig95** [comment]
> Anyway for now actually there is already the beam of light pointing which checkpoint you should reach, we can still change the color of the platform if it's not clear enough but I would play on the beam, maybe make it way taller

I did not notice that the beam effect disappears, then I agree with you. Maybe let's use this issue just to make the transition more visible

**Comment by TizioMaurizio** [comment]
probably making the beam like 5 times taller will make it easier also to find the next checkpoint when it's hidden, we just have to try it out
