### ISSUE TITLE
Hide better the layer between reality platform and intangible noclip object

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#136]
This is probably a minor fix, we can also avoid to have these types of interfaces, but sometimes it's possible to notice when the intangible object begins even in reality mode.

Here is an example, where the player should walk on the bridge and "jump" over the gap.
![image](https://user-images.githubusercontent.com/36990714/204377340-778e3a84-d398-4e62-a36d-6bb6b5689c4b.png)

**Comment by azazellus** [comment]
Yes, the new levels should have fixed this problem!
