### ISSUE TITLE
activate noclip mode only after checkpoint

### ISSUE THREAD

**Issue by stefanofossati** [VDP-noclip/noclip#158]
now the noclip mode can be activated even if the player  haven't activated the checkpoint yet: it's better that the noclip mode can be activated only if the player has activated the checkpoint

**Comment by spig95** [comment]
Is this feature still needed? For the area-00 tutorial, I think that we can simply deactivate the noclip enabler box collider from the first checkpoints, and enable it once the player needs to noclip. 

If you need this feature for following areas, I can implement a minor change to `AnchorCheckpointController`
