### ISSUE TITLE
Correct the saving of the audio data

### ISSUE THREAD

**Issue by stefanofossati** [VDP-noclip/noclip#173]
Now we cannot set the audio from the mixer because the player.pref overwrite the value. 
- Redesign the implementation of the audio setting of the player;
- Create more specific channels in order to be more flexible on the equalization
- audio track when the mode change is missing

**Comment by bottolo** [comment]
What would you suggest? Do we have to get rid of player prefs? I still think they could be useful to us!

Another thing is: do we really need that many channels? I've deleted some unused channels because there were too many.
