### ISSUE TITLE
Music changes in noclip mode and pause menu

### ISSUE THREAD

**Issue by azazellus** [VDP-noclip/noclip#181]
- In pause it would be cool if the background music was muffled (maybe lowering down the high frequencies).
- In noclip mode it could be even better if there was a new music layer added to the normal background song.

**Comment by bottolo** [comment]
I'm aware of this. Once my degree is all sorted out, I'll look into it with Stefano.

**Comment by spig95** [comment]
I don't know if you still want this feature, but adding an audio track layer if we are in noclip mode or when we can enable noclip is pretty easy. I made a branch that should (hopefully) have this feature. You can give it a try and we can make a PR if we want to keep it. 

You can select the options using the `DeaultAudioTracks` scriptable object. At the moment, in my commit, I have put volume 0 to the audio tracks related to this feature.

https://github.com/VDP-noclip/noclip/tree/spig/add-music-layers-baed-on-noclip-states
