### ISSUE TITLE
Investigate methods to lock the aspect ratio to 16:9

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#185]
This is a follow up to the widescreen issue that @AleDeNic noticed when a friend played noclip. 
If possible, we need to make sure that noclip doesn't spread on wide monitors... because it just isn't playable on different aspect ratios. 

There are two main possible ways to handle this:
- Lock the aspect ratio to 16:9.
- Actually implement the most common aspect ratios and properly detect them when the game boots up.

**Comment by stefanofossati** [comment]
This issue is solved in the PR #264
