### ISSUE TITLE
Fix sound effects audio

### ISSUE THREAD

**Issue by TizioMaurizio** [VDP-noclip/noclip#196]
Sound effects audio seems to lower volume during play, especially after pause, also noclip sound effect doesn't play when noclipping detached from ground

**Comment by bottolo** [comment]
Yes, I'm aware of this. I've experienced this just a day after uploading the game to itch lol. It happened after I've tried to muffle sound from the pause menu.

**Comment by TizioMaurizio** [comment]
is this fixed or we leave the issue open?
