### ISSUE TITLE
If we press TAB to skip the loading screen, the player does not respawn properly in the new area

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#233]
If we finish area_00 and we press TAB in the loading screen, the player does not spawn in area_01, but falls down. I guess this is related to the fact that tab also tries to respawn the new player, but the checkpoints values are not yet updated. 

My ideas are: either disable the "tab" option until we do not reach the first checkpoint, or specify a different button to skip the loading screen animation. The second one is easier. Other proposals?

**Comment by stefanofossati** [comment]
The reason is that TAB allows to skip puzzles, so if you press it during the loading screen the player respawn in the next puzzle that isn't loaded
