### ISSUE TITLE
Specify also a keyboard key to enable noclip and add related instructions

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#255]
Let's be friendly to the (hopefully ;) ) few people that will try the game without a keyboard, and put a key to enable noclip!

This is not a lot of work from the code perspective, we just need to discuss and decide which key to use, and put the instructions in the dialogues + menu.

**Comment by stefanofossati** [comment]
@AleDeNic  a dialogue is missing in area 01 in order to activate noclip mode

**Comment by stefanofossati** [comment]
the PR #293 introduces a new key for activate the noclip mode from the keyboard
