### ISSUE TITLE
The sensitivity of the camera changes drastically when facing a specific direction

### ISSUE THREAD

**Issue by TizioMaurizio** [VDP-noclip/noclip#31]
@AleDeNic if you have more details please write them here

**Comment by azazellus** [comment]
This video shows how mouse sensitivity is affected by the direction the camera is facing (~90° in the puzzle direction)
https://drive.google.com/file/d/1LlhAqjbJOjodoNqydKPJuIzhUCi-JfsR/view?usp=share_link
