### ISSUE TITLE
RealityMovement overhaul

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#33]
This is an issue opened to address code clarity on `RealityMovement `and if it needs overhauling in any way. 

I've seen some comments inside about changing some stuff up and since some things changed since the last iteration of `RealityMovement` I suggest tweaking it before moving forward. 

Feel free to comment if you have any suggestions. I for starters wanted to delete some verbose comments if they're not necessary. But it seems that most of the work has been done by @stefanofossati so maybe it's better to let him expose some issues here and maybe start from there together.

**Comment by bottolo** [comment]
I've created the `realitymovement-overahul` branch, so that even with major changes its PR will be small.

**Comment by TizioMaurizio** [comment]
I guess this shall be just about RealityMovement.cs then, because clean up AllPlayer was supposed to be about everything contained inside it, including the scripts
