### ISSUE TITLE
Transitions, animations, loading screens and proper fonts

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#35]
A placeholder doesn't get the job done. But some real art surely does! 

- Transitions need to be implemented when selecting things from the menu.
- Some basic animations need to be implemented! The idea was to have an animation running on the menu.
- Fonts and logos will have to be changed.

I may split the actual issue in more parts when the time comes.

**Comment by TizioMaurizio** [comment]
Update: puzzle animations are work in progress

**Comment by TizioMaurizio** [comment]
Should we close this issue?

**Comment by stefanofossati** [comment]
the loading screen is impelemnted in PR #209
