### ISSUE TITLE
Narrative sections

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#37]
Of course, narrative sections are different from puzzle sections. How should they behave? Should the player actually _not_ be able to sprint in these sections? Does his movement need to be slowed down?

[In Amnesia: The Dark Descent](https://www.youtube.com/watch?v=1kpeos7nn5k) and such, there's this widely known approach which consists on slowing down the player slightly or preventing him to sprint around while certain narrative events are active. This is to let the player focus on events and dialogues more, and puts more emphasis.

This issue is solely created with narrative levels in mind.

**Comment by stefanofossati** [comment]
in the PR #293 a lot of dialogues are added, so this issue can be close
