### ISSUE TITLE
Post Processing Effects

### ISSUE THREAD

**Issue by bottolo** [VDP-noclip/noclip#46]
This is a reference guide to whoever wants to dive in this issue. I'm currently investigating but I'm afraid I'm not experienced enough to understand how to implement this.

There are multiple ways of handling post processing effects. 

The more convenient method for our purposes is the one involving _LintGammaGain_, which can be accessed like this:
`GameObject` -> `Volume` -> `GlobalVolume` (I would recommend calling it `PostProcessingVolume`). 
Click on the `PostProcessingVolume` and click on "New" on the side, where _Profile_ resides. Then, click on _Add Override_ and add whichever effect you like. To change brightness, I would use _LintGammaGain_, specifically the gamma value.

Whoever comes up with something, I'm all ears.

**Comment by spig95** [comment]
I have tried to play around with your suggestion, but it did not work. In particular, when I play with "Lift, Gamma, Gain", it changes the effects on the scene (editor), but when I play nothing changes in the view. Maybe I missed a step, sorry if I can't help!

As a plan B, the only tutorial on how to adjust brightness which I found is [this](https://www.youtube.com/watch?v=XiJ-kb-NvV4&t=9s), which is complex but should work...

**Comment by bottolo** [comment]
> As a plan B, the only tutorial on how to adjust brightness which I found is [this](https://www.youtube.com/watch?v=XiJ-kb-NvV4&t=9s), which is complex but should work...

I've already seen it, and there's one crucial problem when it comes to his solution. 
He uses a different rendering pipeline for the main camera... which seems to be the problem with how these effect should be implemented. Of course, what we're pursuing should be achieveable from the URP pipeline, but there are different parameters which differ from the ones in the HDRP pipeline he uses, hence the confusion in the implementation.

The fact is that Unity changed something about its pipeline a couple of years ago as I've seen. This invalidated some tutorials here and there, and therefore scattered eventual infos regarding this aspect.

> I have tried to play around with your suggestion, but it did not work. In particular, when I play with "Lift, Gamma, Gain", it changes the effects on the scene (editor), but when I play nothing changes in the view. Maybe I missed a step, sorry if I can't help!

I don't know, the editor sees it but its parameters cannot be changed at runtime. Very confusing.

From today's research I've found [this](https://www.youtube.com/watch?v=JF4t9pNaZxg&t=397s), a snippet which seems to implement something similar to what I've wanted to achieve.

**Comment by bottolo** [comment]
Furthermore, I've tried the latter while diving around. No chance.

**Comment by bottolo** [comment]
I've found a comment [here](https://youtu.be/a0OQvWAPeuo) saying that post processing is possible with a different pipeline, specifically the HDRP. 

I'll look into that to see if it makes any difference and if it's possible to change this project's rendering pipeline.

**Comment by TizioMaurizio** [comment]
Is this still urgent in perspective of delivering a functioning demo? I'm setting to urgent what is absolutely necessary for the 3rd of December

**Comment by bottolo** [comment]
> Is this still urgent in perspective of delivering a functioning demo? I'm setting to urgent what is absolutely necessary for the 3rd of December

As a matter of fact, it isn't. I've removed the `urgent` label.

**Comment by TizioMaurizio** [comment]
> > Is this still urgent in perspective of delivering a functioning demo? I'm setting to urgent what is absolutely necessary for the 3rd of December
> 
> As a matter of fact, it isn't. I've removed the `urgent` label.

anyway i saw them in action in a friend's project and they could be the key for impressive noclip's visuals, still swapping the textures has to be done first

**Comment by bottolo** [comment]
They're amazing tools to work with, but this pipeline doesn't seem to love working with post processing effects that easily...
