### ISSUE TITLE
Investigate the need of using coroutines for heavy methods

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#52]
Go though the functions we wrote and add `Coroutines` when needed. For instance, the DisableNoClip and EnableNoClip methods could be executed in coroutines. I am not sure this will bring benefits, some research is needed before adding them.

**Comment by bottolo** [comment]
If anyone wants to implement `coroutines`, I'll willingly hear about how they work since I don't have the experience with these kind of things in C#.

**Comment by spig95** [comment]
We started to use coroutines and we do not have many heavy updates, I guess we can close this issue.
