### ISSUE TITLE
Group the prefabs into sub-folders

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#53]
We should divide the prefabs into subfolders. For instance:
 - Player
 - Reality Objects
 - NoClipObjects
    - StandardNoClipObjects
    - IntangibleNoClipObjects
  - Platforms
  - Compositions/Scenes (to be discussed when we will start to create levels)
  - Etc...

**Comment by bottolo** [comment]
I agree. More prefabs are being made, and it becomes difficult to keep track. Maybe a mini PR for this?
