### ISSUE TITLE
Low jump while moving on slopes

### ISSUE THREAD

**Issue by azazellus** [VDP-noclip/noclip#62]
The jumps while moving on slopes are very low. I guess this happens because the jump force is contrasted by the perpendicular force applied to the rigitbody to keep it attached to the slope.

Possible solution: disabling the perpendicular force before the jump force is applied to the rigidbody.

**Comment by TizioMaurizio** [comment]
This is now solved in the calibration GUI branch so it can be closed

**Comment by TizioMaurizio** [comment]
hahahah the solution was already here
