### ISSUE TITLE
Add scripts to IntanbigleNoclipObjectsHolder and InvisibleNoclipObjectsHolder

### ISSUE THREAD

**Issue by spig95** [VDP-noclip/noclip#71]
As discussed with @TizioMaurizio, we will put scripts into these prefabs to make sure that the child objects will have the correct tags and layers. Each puzzle, the, should have have the noclip objects as child of these prefabs.

**Comment by TizioMaurizio** [comment]
(obvious implication) this way even if you forget tagging the objects or you do it wrong (they are many) the script will do it for you as long as you grouped them properly, since it is hopefully more hard to get that wrong
